### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by elpiel** [LechevSpace/embedded-canvas#1]
Add more examples in:
- `./examples` directory
- Readme & Crate docs (with images, draw inspiration from https://docs.rs/embedded-graphics)

:heavy_check_mark: **Cropping** - an idea for an example that will show the cropping functionality for a useful use case:

Show a box with an outline and e.g. 3 lines of text. Only the middle line will be fully shown while the others will be partially visible (i.e. cropped) below and above the middle one.
- example provided in #5
- screenshot in commit https://github.com/LechevSpace/embedded-canvas/commit/b91bacea95d9fcc13efe5a6b91fcd244b3f3dcdd

:heavy_check_mark: **Transparency** - create a shape (e.g. a rectangle) filled with a specific color on the display, then create a canvas, draw anything on it with different color and place it inside the rectangle that's been already drawn on the display.
- Example provided in #6

**Comment by thecre8tor** [comment]
I will be working on this project.

**Comment by elpiel** [comment]
Great @TheCre8tor, you can start by adding 1 example in the `/examples` directory.
We can later make the screenshots using the simulator display and add them to Readme & lib.rs

**Comment by thecre8tor** [comment]
Alright @elpiel, I am already on it.

**Comment by thecre8tor** [comment]
Working on the transparency example

**Comment by elpiel** [comment]
Thanks for the contributions @TheCre8tor !
