### ISSUE TITLE
Height / Width flipped for CCanvas

### ISSUE THREAD

**Issue by JoshMcguigan** [LechevSpace/embedded-canvas#14]
Hello! And thanks for your work on embedded-canvas.

https://github.com/LechevSpace/embedded-canvas/blob/970980fbdb7b79c46df2ae59c89f59d849f32666/src/consts.rs#L21-L25

The height and width are flipped in the struct definitions for the const canvas structs. The code indexes in like `[x][y]`, so the struct should look like:

```
pub struct CCanvas<C: PixelColor, const W: usize, const H: usize> {
    // we also store the size for working with embedded-graphics
    pub size: Size,
    pub pixels: [[Option<C>; H]; W],
}
```

**Comment by elpiel** [comment]
Hello @JoshMcguigan ,
Thank you for reporting this issue.
You are right, they seem to be flipped 😅.

Would you like to open a PR for the fix?

Ps: I'd love to see usage of the crate in the wild so if your project is OS do share it here 😋

**Comment by JoshMcguigan** [comment]
Ultimately I was not able to use embedded-canvas on my project due to memory constraints. The project is open source: https://github.com/JoshMcguigan/mesozoic

And here you can see the type of thing I was hoping to improve by using a canvas: https://github.com/JoshMcguigan/mesozoic/blob/main/app/src/display.rs#L65-L68

**Comment by elpiel** [comment]
> Ultimately I was not able to use embedded-canvas on my project due to memory constraints. The project is open source: https://github.com/JoshMcguigan/mesozoic
> 
> And here you can see the type of thing I was hoping to improve by using a canvas: https://github.com/JoshMcguigan/mesozoic/blob/main/app/src/display.rs#L65-L68

Thanks a lot for sharing!
Really interesting project, I will definitely follow it up!
